// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(Exe201WorkshopistaContext))]
    partial class Exe201WorkshopistaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Models.AuditLog", b =>
                {
                    b.Property<Guid>("LogId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("log_id");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<string>("Entity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("entity");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<Guid?>("PerformedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("performed_by");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__AuditLog__9E2397E0273670BF");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CategoryId")
                        .HasName("PK__Category__D54EE9B420B124AB");

                    b.HasIndex(new[] { "Slug" }, "UQ__Category__32DD1E4C475F73D5")
                        .IsUnique()
                        .HasFilter("([slug] IS NOT NULL)");

                    b.HasIndex(new[] { "Name" }, "UQ__Category__72E12F1B8F3F9A5C")
                        .IsUnique()
                        .HasFilter("([name] IS NOT NULL)");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("c74797ba-bb5d-46ea-9574-8b7dbe75c4f3"),
                            CreatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3667),
                            Description = "Workshops focused on business skills, entrepreneurship, and management.",
                            Name = "Business",
                            Slug = "business",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3672)
                        },
                        new
                        {
                            CategoryId = new Guid("27ae5c53-f0b7-4f71-b52a-52b78511fb01"),
                            CreatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3675),
                            Description = "Workshops on software development, AI, cloud computing, and emerging technologies.",
                            Name = "Technology",
                            Slug = "technology",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3676)
                        },
                        new
                        {
                            CategoryId = new Guid("8f40d269-eaa5-42d7-9d15-97d9bb147a6d"),
                            CreatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3695),
                            Description = "Creative workshops covering arts, crafts, and design.",
                            Name = "Arts & Crafts",
                            Slug = "arts-and-crafts",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3696)
                        },
                        new
                        {
                            CategoryId = new Guid("e1670a2c-2ea1-474a-a882-28c575df7f81"),
                            CreatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3698),
                            Description = "Workshops focused on fitness, mental health, and overall well-being.",
                            Name = "Health & Wellness",
                            Slug = "health-wellness",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3699)
                        },
                        new
                        {
                            CategoryId = new Guid("3ddf752c-eed5-42c8-93b9-4cd316135a19"),
                            CreatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3701),
                            Description = "Workshops aimed at personal growth, leadership, and career development.",
                            Name = "Personal Development",
                            Slug = "personal-development",
                            Status = "Active",
                            UpdatedAt = new DateTime(2024, 9, 30, 5, 59, 1, 369, DateTimeKind.Utc).AddTicks(3701)
                        });
                });

            modelBuilder.Entity("Repository.Models.Commission", b =>
                {
                    b.Property<Guid>("CommissionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("commission_id");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TotalCommission")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_commission");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("CommissionId")
                        .HasName("PK__Commissi__D19D7CC90A4035D4");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_Commission_workshop_id");

                    b.ToTable("Commission", (string)null);
                });

            modelBuilder.Entity("Repository.Models.CommissionTransaction", b =>
                {
                    b.Property<Guid>("CommissionTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("commission_transaction_id");

                    b.Property<decimal?>("CommissionRate")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("CommissionTransactionId")
                        .HasName("PK__Commissi__32A99DDF3CA1F70E");

                    b.HasIndex(new[] { "TransactionId" }, "IX_CommissionTransaction_transaction_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_CommissionTransaction_workshop_id");

                    b.ToTable("CommissionTransaction", (string)null);
                });

            modelBuilder.Entity("Repository.Models.EventAnalytic", b =>
                {
                    b.Property<Guid>("AnalyticsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("analytics_id");

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(2, 1)")
                        .HasColumnName("average_rating");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_revenue");

                    b.Property<int?>("TotalReviews")
                        .HasColumnType("int")
                        .HasColumnName("total_reviews");

                    b.Property<int?>("TotalTicketsSold")
                        .HasColumnType("int")
                        .HasColumnName("total_tickets_sold");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("AnalyticsId")
                        .HasName("PK__EventAna__D5DC3DE1912B45AA");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_EventAnalytics_workshop_id");

                    b.ToTable("EventAnalytics");
                });

            modelBuilder.Entity("Repository.Models.News", b =>
                {
                    b.Property<Guid>("NewsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("news_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("published_at");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NewsId")
                        .HasName("PK__News__4C27CCD8D61AD16C");

                    b.HasIndex(new[] { "Slug" }, "UQ__News__32DD1E4CEEFB436D")
                        .IsUnique()
                        .HasFilter("([slug] IS NOT NULL)");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("participant_id");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_status");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_time");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("OrderId")
                        .HasName("PK__Order__46596229D5600F2F");

                    b.HasIndex(new[] { "ParticipantId" }, "IX_Order_participant_id");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("Repository.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_details_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("OrderDetailsId")
                        .HasName("PK__OrderDet__F6FB5AE4C762AF40");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetails_order_id");

                    b.HasIndex(new[] { "TicketId" }, "IX_OrderDetails_ticket_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_OrderDetails_workshop_id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Repository.Models.Organizer", b =>
                {
                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organizer_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("organization_name");

                    b.Property<string>("SocialLinks")
                        .HasColumnType("text")
                        .HasColumnName("social_links");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<bool?>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("website_url");

                    b.HasKey("OrganizerId")
                        .HasName("PK__Organize__06347014B8E42884");

                    b.HasIndex(new[] { "UserId" }, "IX_Organizer_user_id");

                    b.ToTable("Organizer", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Otp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsUsed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("OTP", (string)null);
                });

            modelBuilder.Entity("Repository.Models.PaymentMethod", b =>
                {
                    b.Property<Guid>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MethodName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("method_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__8A3EA9EBF19ACE4A");

                    b.ToTable("PaymentMethod", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Promotion", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promotion_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organizer_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("PromotionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("promotion_type");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__2CB9556B36D75614");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_Promotion_organizer_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_Promotion_workshop_id");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("Repository.Models.PromotionTransaction", b =>
                {
                    b.Property<Guid>("PromotionTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promotion_transaction_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("promotion_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("PromotionTransactionId")
                        .HasName("PK__Promotio__A5C4F6151910D125");

                    b.HasIndex(new[] { "PromotionId" }, "IX_PromotionTransaction_promotion_id");

                    b.HasIndex(new[] { "TransactionId" }, "IX_PromotionTransaction_transaction_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_PromotionTransaction_workshop_id");

                    b.ToTable("PromotionTransaction", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("review_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("ParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("participant_id");

                    b.Property<short?>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("ReviewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("ReviewId")
                        .HasName("PK__Review__60883D90378C5259");

                    b.HasIndex(new[] { "ParticipantId" }, "IX_Review_participant_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_Review_workshop_id");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<bool?>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("StartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__Subscrip__863A7EC1993FA16B");

                    b.HasIndex(new[] { "UserId" }, "IX_Subscription_user_id");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("Repository.Models.SubscriptionTransaction", b =>
                {
                    b.Property<Guid>("SubscriptionTransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_transaction_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SubscriptionTransactionId")
                        .HasName("PK__Subscrip__762A0D4C91ACD385");

                    b.HasIndex(new[] { "SubscriptionId" }, "IX_SubscriptionTransaction_subscription_id");

                    b.HasIndex(new[] { "TransactionId" }, "IX_SubscriptionTransaction_transaction_id");

                    b.ToTable("SubscriptionTransaction", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("OrderDetailId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("order_detail_id");

                    b.Property<DateTime?>("PaymentTime")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_time");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("QrCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TicketRankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_rank_id");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("TicketId")
                        .HasName("PK__Ticket__D596F96B7099B05A");

                    b.HasIndex(new[] { "OrderDetailId" }, "IX_Ticket_order_detail_id");

                    b.HasIndex(new[] { "TicketRankId" }, "IX_Ticket_ticket_rank_id");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_Ticket_workshop_id");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("Repository.Models.TicketRank", b =>
                {
                    b.Property<Guid>("TicketRankId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_rank_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("rank_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("TicketRankId")
                        .HasName("PK__TicketRa__1B8160B1D43B79A1");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_TicketRank_workshop_id");

                    b.ToTable("TicketRank", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("transaction_id");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_method_id");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("transaction_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__85C600AF4A720ABE");

                    b.HasIndex(new[] { "PaymentMethodId" }, "IX_Transaction_payment_method_id");

                    b.HasIndex(new[] { "UserId" }, "IX_Transaction_user_id");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Repository.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_verified");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool?>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__User__B9BE370F4336E3EF");

                    b.HasIndex(new[] { "Email" }, "UQ__User__AB6E616457DE1028")
                        .IsUnique()
                        .HasFilter("([email] IS NOT NULL)");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("30c18893-99f0-49b9-98fb-18a990489f87"),
                            Email = "admin@gmail.com",
                            EmailVerified = true,
                            FirstName = "Alice",
                            LastName = "Smith",
                            PasswordHash = "$2a$11$ASMuiRckojlJiy4wEYzSU.dZ3mrYOGvO0QmfkD8I/H0kgSkMJQqiK",
                            PhoneNumber = "1234567890",
                            PhoneVerified = true,
                            ProfileImageUrl = "https://i0.wp.com/fdlc.org/wp-content/uploads/2021/01/157-1578186_user-profile-default-image-png-clipart.png.jpeg?fit=880%2C769&ssl=1",
                            Role = "Admin",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("382359c6-916d-4548-8583-1a0807f57b7e"),
                            Email = "org@gmail.com",
                            EmailVerified = true,
                            FirstName = "Bob",
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$hClCjcawkPoEaPyI8VO3RuH592yCe53DtEvPe/aRPk6bKKROCGREO",
                            PhoneNumber = "9876543210",
                            PhoneVerified = true,
                            ProfileImageUrl = "https://i0.wp.com/fdlc.org/wp-content/uploads/2021/01/157-1578186_user-profile-default-image-png-clipart.png.jpeg?fit=880%2C769&ssl=1",
                            Role = "Organizer",
                            Status = "Active"
                        },
                        new
                        {
                            UserId = new Guid("70cfded3-8d98-4a54-ac62-ff6478450c3b"),
                            Email = "charlie@example.com",
                            EmailVerified = true,
                            FirstName = "Charlie",
                            LastName = "Brown",
                            PasswordHash = "$2a$11$BopGOIlJDnHg8v3Fv6ROxOEEDsYiEwSW683DSMfy6CST1TQS8JvvK",
                            PhoneNumber = "5551234567",
                            PhoneVerified = true,
                            ProfileImageUrl = "https://i0.wp.com/fdlc.org/wp-content/uploads/2021/01/157-1578186_user-profile-default-image-png-clipart.png.jpeg?fit=880%2C769&ssl=1",
                            Role = "Organizer",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("Repository.Models.Workshop", b =>
                {
                    b.Property<Guid>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location_address");

                    b.Property<string>("LocationCity")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location_city");

                    b.Property<string>("LocationDistrict")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location_district");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)")
                        .HasColumnName("longitude");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("organizer_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("price");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("video_url");

                    b.HasKey("WorkshopId")
                        .HasName("PK__Workshop__EA6B0559D8B60A03");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Workshop_category_id");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_Workshop_organizer_id");

                    b.HasIndex(new[] { "Slug" }, "UQ__Workshop__32DD1E4CC1ABD095")
                        .IsUnique()
                        .HasFilter("([slug] IS NOT NULL)");

                    b.ToTable("Workshop", (string)null);
                });

            modelBuilder.Entity("Repository.Models.WorkshopImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("image_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid?>("WorkshopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workshop_id");

                    b.HasKey("ImageId")
                        .HasName("PK__Workshop__DC9AC9555C0A8683");

                    b.HasIndex(new[] { "WorkshopId" }, "IX_WorkshopImage_workshop_id");

                    b.ToTable("WorkshopImage", (string)null);
                });

            modelBuilder.Entity("Repository.Models.Commission", b =>
                {
                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("Commissions")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__Commissio__works__2645B050");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.CommissionTransaction", b =>
                {
                    b.HasOne("Repository.Models.Transaction", "Transaction")
                        .WithMany("CommissionTransactions")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_CommissionTransaction_Transaction");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("CommissionTransactions")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK_CommissionTransaction_Workshop");

                    b.Navigation("Transaction");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.EventAnalytic", b =>
                {
                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("EventAnalytics")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__EventAnal__works__22751F6C");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.HasOne("Repository.Models.User", "Participant")
                        .WithMany("Orders")
                        .HasForeignKey("ParticipantId")
                        .HasConstraintName("FK__Order__participa__1AD3FDA4");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Repository.Models.OrderDetail", b =>
                {
                    b.HasOne("Repository.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__OrderDeta__order__1BC821DD");

                    b.HasOne("Repository.Models.Ticket", "Ticket")
                        .WithMany("OrderDetails")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("FK__OrderDeta__ticke__1DB06A4F");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("OrderDetails")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__OrderDeta__works__1CBC4616");

                    b.Navigation("Order");

                    b.Navigation("Ticket");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Organizer", b =>
                {
                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Organizers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Organizer__user___0D7A0286");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.Otp", b =>
                {
                    b.HasOne("Repository.Models.User", "CreatedByNavigation")
                        .WithMany("Otps")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_OTP_User");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Repository.Models.Promotion", b =>
                {
                    b.HasOne("Repository.Models.Organizer", "Organizer")
                        .WithMany("Promotions")
                        .HasForeignKey("OrganizerId")
                        .HasConstraintName("FK__Promotion__organ__245D67DE");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("Promotions")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__Promotion__works__25518C17");

                    b.Navigation("Organizer");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.PromotionTransaction", b =>
                {
                    b.HasOne("Repository.Models.Promotion", "Promotion")
                        .WithMany("PromotionTransactions")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK_PromotionTransaction_Promotion");

                    b.HasOne("Repository.Models.Transaction", "Transaction")
                        .WithMany("PromotionTransactions")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_PromotionTransaction_Transaction");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("PromotionTransactions")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK_PromotionTransaction_Workshop");

                    b.Navigation("Promotion");

                    b.Navigation("Transaction");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Review", b =>
                {
                    b.HasOne("Repository.Models.User", "Participant")
                        .WithMany("Reviews")
                        .HasForeignKey("ParticipantId")
                        .HasConstraintName("FK_Review_User");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("Reviews")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__Review__workshop__208CD6FA");

                    b.Navigation("Participant");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Subscription", b =>
                {
                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Subscript__user___236943A5");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.SubscriptionTransaction", b =>
                {
                    b.HasOne("Repository.Models.Subscription", "Subscription")
                        .WithMany("SubscriptionTransactions")
                        .HasForeignKey("SubscriptionId")
                        .HasConstraintName("FK_SubscriptionTransaction_Subscription");

                    b.HasOne("Repository.Models.Transaction", "Transaction")
                        .WithMany("SubscriptionTransactions")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("FK_SubscriptionTransaction_Transaction");

                    b.Navigation("Subscription");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Repository.Models.Ticket", b =>
                {
                    b.HasOne("Repository.Models.OrderDetail", "OrderDetail")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderDetailId")
                        .HasConstraintName("FK_Ticket_OrderDetails");

                    b.HasOne("Repository.Models.TicketRank", "TicketRank")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketRankId")
                        .HasConstraintName("FK_Ticket_TicketRank");

                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("Tickets")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__Ticket__workshop__114A936A");

                    b.Navigation("OrderDetail");

                    b.Navigation("TicketRank");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.TicketRank", b =>
                {
                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("TicketRanks")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK_TicketRank_Workshop");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Transaction", b =>
                {
                    b.HasOne("Repository.Models.PaymentMethod", "PaymentMethod")
                        .WithMany("Transactions")
                        .HasForeignKey("PaymentMethodId")
                        .HasConstraintName("FK__Transacti__payme__14270015");

                    b.HasOne("Repository.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Transaction_User");

                    b.Navigation("PaymentMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Models.Workshop", b =>
                {
                    b.HasOne("Repository.Models.Category", "Category")
                        .WithMany("Workshops")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Workshop__catego__0F624AF8");

                    b.HasOne("Repository.Models.Organizer", "Organizer")
                        .WithMany("Workshops")
                        .HasForeignKey("OrganizerId")
                        .HasConstraintName("FK__Workshop__organi__0E6E26BF");

                    b.Navigation("Category");

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("Repository.Models.WorkshopImage", b =>
                {
                    b.HasOne("Repository.Models.Workshop", "Workshop")
                        .WithMany("WorkshopImages")
                        .HasForeignKey("WorkshopId")
                        .HasConstraintName("FK__WorkshopI__works__10566F31");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("Repository.Models.Category", b =>
                {
                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Repository.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Repository.Models.OrderDetail", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Repository.Models.Organizer", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("Workshops");
                });

            modelBuilder.Entity("Repository.Models.PaymentMethod", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Repository.Models.Promotion", b =>
                {
                    b.Navigation("PromotionTransactions");
                });

            modelBuilder.Entity("Repository.Models.Subscription", b =>
                {
                    b.Navigation("SubscriptionTransactions");
                });

            modelBuilder.Entity("Repository.Models.Ticket", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Repository.Models.TicketRank", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Repository.Models.Transaction", b =>
                {
                    b.Navigation("CommissionTransactions");

                    b.Navigation("PromotionTransactions");

                    b.Navigation("SubscriptionTransactions");
                });

            modelBuilder.Entity("Repository.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Organizers");

                    b.Navigation("Otps");

                    b.Navigation("Reviews");

                    b.Navigation("Subscriptions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Repository.Models.Workshop", b =>
                {
                    b.Navigation("CommissionTransactions");

                    b.Navigation("Commissions");

                    b.Navigation("EventAnalytics");

                    b.Navigation("OrderDetails");

                    b.Navigation("PromotionTransactions");

                    b.Navigation("Promotions");

                    b.Navigation("Reviews");

                    b.Navigation("TicketRanks");

                    b.Navigation("Tickets");

                    b.Navigation("WorkshopImages");
                });
#pragma warning restore 612, 618
        }
    }
}
